use rusty_procgen_preflight::core::ProcgenCore;
use serde::Serialize;

use crate::{RUSTY_ENGINE_REVISION, RUSTY_PROCGEN_REVISION};

pub const BOOTSTRAP_SCHEMA_VERSION: u32 = 1;

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BootstrapReadout {
    pub schema_version: u32,
    pub product: &'static str,
    pub phase: &'static str,
    pub rusty_engine_revision: &'static str,
    pub rusty_procgen_revision: &'static str,
    pub procgen_link_hash: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ProcgenLinkProbe<'a> {
    product: &'a str,
    revision: &'a str,
}

pub fn bootstrap_readout() -> BootstrapReadout {
    let procgen_link_hash = ProcgenCore::canonical_hash(&ProcgenLinkProbe {
        product: "rusty-roguelike",
        revision: RUSTY_PROCGEN_REVISION,
    })
    .expect("the fixed bootstrap probe is canonically serializable");

    BootstrapReadout {
        schema_version: BOOTSTRAP_SCHEMA_VERSION,
        product: "rusty-roguelike",
        phase: "bootstrap",
        rusty_engine_revision: RUSTY_ENGINE_REVISION,
        rusty_procgen_revision: RUSTY_PROCGEN_REVISION,
        procgen_link_hash,
    }
}

pub fn generated_typescript() -> String {
    let candidate = crate::rules::generated_candidate_typescript();
    let world = crate::world::generated_world_typescript();
    let session = crate::session::generated_session_typescript();
    format!(
        "// GENERATED by `cargo run --manifest-path rust/Cargo.toml -p rusty-roguelike --bin rusty-roguelike-protocol`. Do not hand-edit.\n\n\
export const BOOTSTRAP_SCHEMA_VERSION = {BOOTSTRAP_SCHEMA_VERSION} as const;\n\
export const RUSTY_ENGINE_REVISION = '{RUSTY_ENGINE_REVISION}' as const;\n\
export const RUSTY_PROCGEN_REVISION = '{RUSTY_PROCGEN_REVISION}' as const;\n\n\
export type BootstrapReadoutDto = {{\n\
  readonly schemaVersion: typeof BOOTSTRAP_SCHEMA_VERSION;\n\
  readonly product: 'rusty-roguelike';\n\
  readonly phase: 'bootstrap';\n\
  readonly rustyEngineRevision: typeof RUSTY_ENGINE_REVISION;\n\
  readonly rustyProcgenRevision: typeof RUSTY_PROCGEN_REVISION;\n\
  readonly procgenLinkHash: string;\n\
}};\n\n\
{candidate}

{world}

{session}"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bootstrap_readout_links_exact_public_dependencies_deterministically() {
        let first = bootstrap_readout();
        let second = bootstrap_readout();
        assert_eq!(first, second);
        assert_eq!(first.schema_version, 1);
        assert_eq!(first.product, "rusty-roguelike");
        assert_eq!(first.phase, "bootstrap");
        assert_eq!(first.rusty_engine_revision.len(), 40);
        assert_eq!(first.rusty_procgen_revision.len(), 40);
        assert!(first.procgen_link_hash.starts_with("fnv1a64:"));
        assert_eq!(first.procgen_link_hash.len(), 24);
    }

    #[test]
    fn committed_typescript_protocol_matches_the_rust_owner() {
        assert_eq!(
            generated_typescript(),
            include_str!("../../../../libs/protocol/src/generated/api-types.ts")
        );
    }
}
