autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': true
  '@rusty-engine/render-contracts@https://codeload.github.com/FuzzySlipper/rusty-engine/tar.gz/b1f0415af6266783246371d227a2272de7d9f0d6#path:render/packages/render-contracts': true
  '@rusty-engine/render-projection@https://codeload.github.com/FuzzySlipper/rusty-engine/tar.gz/b1f0415af6266783246371d227a2272de7d9f0d6#path:render/packages/render-projection': true
  '@rusty-engine/renderer-host@https://codeload.github.com/FuzzySlipper/rusty-engine/tar.gz/b1f0415af6266783246371d227a2272de7d9f0d6#path:render/packages/renderer-host': true
  '@rusty-engine/renderer-three@https://codeload.github.com/FuzzySlipper/rusty-engine/tar.gz/b1f0415af6266783246371d227a2272de7d9f0d6#path:render/packages/renderer-three': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
