/**
 * Actor definitions: the lantern-company party and the dormant opposition.
 * Every entityId and stat is preserved exactly in the committed
 * `data/gameplay/rusty-roguelike-starter.package.json` artifact — do not
 * renumber or deduplicate the opposition archetypes.
 */

import { abilityScore, actor, type ActorDefinition } from '../authoring/mod.js';

const scores = (
  might: number,
  finesse: number,
  intellect: number,
  spirit: number,
) => [
  abilityScore('might', might),
  abilityScore('finesse', finesse),
  abilityScore('intellect', intellect),
  abilityScore('spirit', spirit),
];

const goblinRaider = (
  value: string,
  entityId: number,
  name: string,
  title: string,
  vitality: number,
  might: number,
  finesse: number,
  intellect: number,
  spirit: number,
): ActorDefinition =>
  actor(value, entityId, name, title, 'opposition', {
    vitality,
    inventoryCapacity: 4,
    class: 'goblin-raider',
    abilities: scores(might, finesse, intellect, spirit),
    actions: ['move', 'rusty-blade'],
    feats: ['goblin-cunning'],
    items: ['rusty-knife'],
  });

const emberEye = (
  value: string,
  entityId: number,
  name: string,
  title: string,
  vitality: number,
  might: number,
  finesse: number,
  intellect: number,
  spirit: number,
): ActorDefinition =>
  actor(value, entityId, name, title, 'opposition', {
    vitality,
    inventoryCapacity: 4,
    class: 'ember-eye',
    abilities: scores(might, finesse, intellect, spirit),
    actions: ['move', 'ember-shot'],
    feats: ['burning-gaze'],
    items: ['ember-focus'],
  });

export const actors: readonly ActorDefinition[] = [
  actor('brann', 101, 'Brann', 'Shield of the Road', 'party', {
    vitality: 28,
    inventoryCapacity: 8,
    class: 'guardian',
    abilities: scores(16, 11, 9, 12),
    actions: ['move', 'guardian-strike', 'sweeping-strike'],
    feats: ['hold-the-line'],
    items: ['longsword', 'scale-mail'],
  }),
  actor('kestrel', 102, 'Kestrel', 'Pathfinder', 'party', {
    vitality: 21,
    inventoryCapacity: 8,
    class: 'scout',
    abilities: scores(10, 17, 12, 11),
    actions: ['move', 'aimed-shot', 'quick-shot'],
    feats: ['defensive-mobility'],
    items: ['shortbow', 'leather-armor'],
  }),
  actor('mira', 103, 'Mira', 'Lantern Adept', 'party', {
    vitality: 18,
    inventoryCapacity: 8,
    class: 'arcanist',
    abilities: scores(8, 12, 17, 15),
    actions: ['move', 'arcane-bolt', 'flame-burst', 'mind-spike'],
    feats: ['arcane-focus'],
    items: ['ash-staff', 'focus-orb', 'traveling-robes'],
  }),
  goblinRaider(
    'goblin-scrapper',
    201,
    'Goblin Scrapper',
    'Dormant Raider',
    12,
    11,
    14,
    8,
    9,
  ),
  emberEye(
    'ember-watcher',
    202,
    'Ember Watcher',
    'Dormant Sentinel',
    14,
    8,
    12,
    11,
    15,
  ),
  goblinRaider(
    'tunnel-runner',
    104,
    'Tunnel Runner',
    'Knife in the Dark',
    9,
    9,
    15,
    8,
    9,
  ),
  emberEye('cinder-eye', 105, 'Cinder Eye', 'Ashen Lookout', 10, 7, 13, 10, 14),
  goblinRaider(
    'slag-cutpurse',
    106,
    'Slag Cutpurse',
    'Ruin Lurker',
    9,
    10,
    14,
    9,
    8,
  ),
  goblinRaider(
    'ash-skirmisher',
    107,
    'Ash Skirmisher',
    'Cinder Vanguard',
    11,
    12,
    13,
    8,
    9,
  ),
  emberEye(
    'furnace-lookout',
    108,
    'Furnace Lookout',
    'Coal-Eyed Sentry',
    12,
    8,
    12,
    12,
    14,
  ),
  goblinRaider(
    'soot-stalker',
    109,
    'Soot Stalker',
    'Smoke-Shrouded Knife',
    9,
    9,
    15,
    9,
    8,
  ),
  emberEye(
    'coal-sentry',
    110,
    'Coal Sentry',
    'Banked-Flame Guard',
    13,
    9,
    11,
    11,
    15,
  ),
  goblinRaider(
    'clinker-knife',
    111,
    'Clinker Knife',
    'Rubble Ambusher',
    10,
    10,
    14,
    8,
    10,
  ),
  emberEye(
    'flare-watcher',
    112,
    'Flare Watcher',
    'Bright-Eyed Hunter',
    11,
    7,
    13,
    12,
    14,
  ),
  goblinRaider(
    'ruin-scuttler',
    113,
    'Ruin Scuttler',
    'Broken-Stone Prowler',
    9,
    9,
    15,
    8,
    9,
  ),
  emberEye(
    'ember-seer',
    114,
    'Ember Seer',
    'Furnace Oracle',
    14,
    8,
    12,
    13,
    15,
  ),
  goblinRaider(
    'slag-runner',
    115,
    'Slag Runner',
    'Molten-Track Raider',
    10,
    11,
    14,
    8,
    9,
  ),
  goblinRaider(
    'cinder-stalker',
    116,
    'Cinder Stalker',
    'Last-Light Pursuer',
    11,
    10,
    15,
    9,
    8,
  ),
];
