[workspace]
members = ["crates/rusty-roguelike"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
core-ids = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
core-space = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
core-voxel = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
entity-state = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
gameplay-mechanics = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
gameplay-rules = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
svc-collision = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
svc-pathfinding = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
svc-rng = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
svc-spatial = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
svc-volume = { git = "https://github.com/FuzzySlipper/rusty-engine", rev = "fb608e323a8b44a55195f5720101224ff37fd5db" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["macros", "net", "rt-multi-thread"] }
tower-http = { version = "0.6.6", features = ["fs"] }
ts-rs = { version = "11.0.1", features = ["serde-compat"] }
rusty-procgen-preflight = { git = "https://github.com/FuzzySlipper/rusty-procgen", rev = "722e2c479bdf88ab39b66d2d33ab466b698ec7df", package = "rusty-procgen-preflight" }
